# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: setup Node.js environment
      run: actions/setup-node@v2-beta
      with:
        version: 12

    - name: GitHub Action for NPM/Chrome
      uses: daleobrien/npm-with-chrome-browser-action@v1.0.1
      with:
        cmd: install
    - name: creating build
      run: npm run build
        
    - name: Installing surge
      run: npm install --global surge
    - name: Deploying using surge
      run: surge ./ bcs2.surge.sh --token ${{ secrets.SURGE }}
        
